[package]
name = "crate-3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crate-1={git="ssh://git@github.com/kenkoooo/git-cargo-dependency-demo.git",rev="3ac502d647cbb3afa27d89dbedba23d1bc2df935"}
